WebVanPhongPhamHKShop/Controllers/GioiThieuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebVanPhongPhamHKShop.Controllers
{
    public class GioiThieuController : Controller
    {
        // GET: GioiThieu
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebVanPhongPhamHKShop/Controllers/HKShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebVanPhongPhamHKShop.Models;
using PagedList;
using PagedList.Mvc;

namespace WebVanPhongPhamHKShop.Controllers
{
    public class HKShopController : Controller
    {
        dbQLVanPhongPhamDataContext data = new dbQLVanPhongPhamDataContext();//Tao database de goi table

        private List<MatHang> LayMatHangMoi(int count)
        {
            return data.MatHangs.OrderByDescending(a => a.NgaySX).Take(count).ToList();//lay cac mat hang moi, so luong la count
            
        }

        public ActionResult Index(int ? page)
        {
            int pageSize = 6;//Tao bien quy dinh so san pham tren 1 trang
            int pageNum = (page ?? 1);//tao bien so trang
            var MHMoi = LayMatHangMoi(10);//Lay 10 mat hang moi
            return View(MHMoi.ToPagedList(pageNum,pageSize));//tao view hien thi 5 mat hang moi
        }

        public ActionResult DanhMuc()
        {
            var danhMuc = from dm in data.DanhMucs select dm;
            return PartialView(danhMuc);//PartialView hien thi danh muc tai menu, can them code vao _LayoutUser o cho menu de hien thi dung
        }

        public ActionResult SPTheoDanhMuc(int id)
        {
            var mH = from s in data.MatHangs where s.MaDM == id select s;//Hien thi san pham theo danh muc
            return View(mH);
        }

        public ActionResult Detail(int id)
        {
            var mH = from s in data.MatHangs where s.MaMH == id select s;//Hien thi thong tin chi tiet san pham
            return View(mH.Single());
        }

        public ActionResult BaoHanh()
        {
            return View();
        }
    }
}

WebVanPhongPhamHKShop/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebVanPhongPhamHKShop.Models;

namespace WebVanPhongPhamHKShop.Controllers
{
    public class NguoiDungController : Controller
    {
        dbQLVanPhongPhamDataContext db = new dbQLVanPhongPhamDataContext();//Tao databsase de dua thong tin va lay thong tin tu cac bang
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]//hien view
        public ActionResult DangKy()
        {
            return View();
        }
        
        [HttpPost]//dua du lieu vao
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["HotenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var email = collection["Email"];
            var diachi = collection["Diachi"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["Ngaysinh"]);
            if(String.IsNullOrEmpty(hoten))//neu de trong thi hien thi loi
            {
                ViewData["Loi1"] = "*Họ tên khách hàng không được để trống";
            }
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "*Phải nhập tên đăng nhập";
            }
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "*Phải nhập mật khẩu";
            }
            if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "*Phải nhập lại mật khẩu";
            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "*Email không được bỏ trống";
            }
            if (String.IsNullOrEmpty(diachi))
            {
                ViewData["Loi6"] = "*Vui lòng nhập địa chỉ";
            }
            if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi7"] = "*Phải nhập điện thoại";
            }
            else
            {
                kh.HoTen = hoten;
                kh.TaiKhoan = tendn;
                kh.MatKhau = matkhau;
                kh.Email = email;
                kh.DiaChiKH = diachi;
                kh.DienThoaiKH = dienthoai;
                kh.NgaySinh = DateTime.Parse(ngaysinh);
                db.KhachHangs.InsertOnSubmit(kh);
                db.SubmitChanges();
            }
            return RedirectToAction("Index", "HKShop");
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {  
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];

            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "*Phải nhập tên đăng nhập";
            }
            if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "*Phải nhập mật khẩu";
            }
            else
            {
                KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == tendn && n.MatKhau == matkhau);
                if (kh != null)
                {
                    Session["Taikhoan"] = kh;
                    Session["hoten"] = kh.HoTen;
                    return RedirectToAction("Index", "HKShop");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
    }
}

WebVanPhongPhamHKShop/Views/Shared/LoginPartial.cshtml
@if (Session["Taikhoan"] != null)
{
    <a href="@Url.Action("Login","Admin")" id="btn_Dangnhap" style="width: 90px; margin-top: 7px; float: right ;  font-size: 15px; text-decoration:none; font-weight:bold; cursor: pointer;">Admin</a>
    <p style="float: right; font-size: 15px; margin-top: 5px; margin-right: 20px; margin-left: -22px">|</p>
    <a href="#" style="width: 90px; margin-right:15px ; margin-top: 7px; float: right ;  font-size: 15px; text-decoration:none; font-weight:bold; cursor: pointer;">Welcome @Session["hoten"].ToString()</a>
    <p style="float: right; font-size: 15px; margin-top: 5px; margin-right: 20px; margin-left: -22px">|</p>
    <a href="@Url.Action("DangNhap","NguoiDung")" id="btn_Dangnhap" style="width: 90px; margin-right:15px ; margin-top: 7px; float: right ;  font-size: 15px; text-decoration:none; font-weight:bold; cursor: pointer;">Thay đổi</a>

}
else
{
    <a href="@Url.Action("Login","Admin")" id="btn_Dangnhap" style="width: 58px; margin-top: 0px; float: right ;  font-size: 15px; text-decoration:none; font-weight:bold; cursor: pointer;">Admin</a>
    <p style="float: right; font-size: 15px; margin-top: 0px; margin-right: 20px; margin-left: -22px">|</p>
    <a href="@Url.Action("DangNhap","NguoiDung")" id="btn_Dangnhap" style="width: 90px; margin-right:25px ; margin-top: 0px; float: right ;  font-size: 15px; text-decoration:none; font-weight:bold; cursor: pointer;">Đăng nhập</a>
    <p style="float: right; font-size: 15px; margin-top: 0px; margin-right: 5px; margin-left: -22px">|</p>
    <a href="@Url.Action("DangKy","NguoiDung")" id="btn_Dangnhap" style="width: 90px; margin-left: 40px; margin-right: -15px ; margin-top: 0px; float: right ;  font-size: 15px; text-decoration:none; font-weight:bold; cursor:pointer">Đăng Ký</a>
}

WebVanPhongPhamHKShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebVanPhongPhamHKShop/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>HK Shop</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link href="~/Content/admin.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container" style="font-family:Tahoma">
        <div class="header">
            <div class="headertop">
                <div class="logo">
                    <a href="@Url.Action("Index","HKShop")" style="font-weight: bold; font-size: 18px; text-decoration: none;"><img src="~/images/logo.png" alt="" width="140px" height="100px"><span>SHOP</span></a>
                </div>
                <div class="lienhe">
                    <span style="font-size: 16px; line-height: 30px; color: blue; width: 230px; display:block; float:left">Giờ làm việc (8:00 - 22:00) </span>
                    <span style="font-size: 16px; line-height: 30px; color: blue;"><img src="~/images/6.png" />0909 112 113</span>
                </div>
                <div class="thongtin">
                    <a href="@Url.Action("Index","HKShop")"> Quay về user</a>
                    <a href="#" style="background-color:darkgrey"> Giới thiệu</a>
                    <a href="#" style="background-color:darkgrey"> Đơn hàng</a>
                    <a href="#" style="background-color:darkgrey"> Bảo hành</a>
                    <a href="#" style="background-color:darkgrey"> Tin tức</a>
                    <a href="#" style="background-color:darkgrey"> Khuyến mãi</a>
                    <a href="#" style="background-color:darkgrey"> Liên hệ</a>
                </div>

                
            </div> <!-- Hết header_top-->
        </div>
        <div class="content" style="width:auto; height: 1295px; background-color: burlywood; background-image: none">
            <div class="menu">
                <!-- Menu -->
                <ul>
                    <li>
                        <a href="#" style="font-size: 20px"><img src="~/images/7.png" /> <strong>Menu</strong></a>

                        <ul class="submenu" style="width: 437px">
                            @Html.ActionLink("Trang chủ", "Index", "Admin")
                            @Html.ActionLink("Quán lý mặt hàng", "Sanpham", "Admin")
                            @Html.ActionLink("Quán lý danh mục", "Danhmuc", "Admin")                         
                        </ul>
                    </li>

                </ul>
            </div> <!-- hết menu-->
            <div>@RenderBody()</div>
        </div>

        <div class="footer" style="background-color:brown">
            <div class="left">
                <a href="#" id="btn_logo" style="margin-left: 15px; margin-top: 15px; margin-bottom: 20px"><img src="/images/logo.png" width="150px" height="65px" sizes="50" /></a> <br />
                <span><img src="/images/5.png" /> Địa chỉ: 111 - Quận 9 - TPHCM</span> <br />
                <span><img src="/images/6.png" /> Diện thoại: 0909 112 113 - 0909 009 009</span> <br />
                <span><img src="/images/11.png" /> Mail: hkshop123@gmail.com</span>
            </div>
            <div class="center">
                <p style="margin-top:24px; margin-bottom: 10px; font-weight:bold;padding-left: 25px;">THÔNG TIN VÀ HƯỚNG DẪN</p> <br />
                <a id="noidung" href="#"><span>></span> Giới thiệu</a> <br />
                <a id="noidung" href="#"><span>></span> Hướng dẫn mua hàng</a> <br />
                <a id="noidung" href="#"><span>></span> Các hình thức thanh toán</a> <br />
                <a id="noidung" href="#"><span>></span> Điều khoản sử dụng</a> <br />
                <a id="noidung" href="#"><span>></span> Bảo hành, đổi trả hàng</a> <br />
                <a id="noidung" href="#"><span>></span> Chính sách bảo mật</a> <br />
            </div>
            <div class="right">
                <p style="margin-top:24px; margin-bottom: 10px; font-weight:bold;padding-left: 25px;">KẾT NỐI VỚI CHÚNG TÔI</p> <br />
                <a href="#" id="icon"><img src="/images/12.png" /></a>
                <a href="#" id="icon"><img src="/images/13.png" /></a>
                <a href="#" id="icon"><img src="/images/14.png" /></a>
                <a href="#" id="icon"><img src="/images/15.png" /></a>
                <a href="#" id="icon"><img src="/images/16.png" /></a>
                <br />
                <p style="margin-top:24px; margin-bottom:-5px; font-weight:bold;padding-left: 25px;">THANH TOÁN ONLINE</p>
                <a id="icon2"><img src="/images/17.png" /></a>
                <a id="icon2"><img src="/images/18.png" /></a>
                <a id="icon2"><img src="/images/19.png" /></a>
                <a id="icon2"><img src="/images/20.png" /></a>

            </div>
        </div> <!-- Hết footer -->

    </div> <!-- Hết container -->
</body>
</html>

WebVanPhongPhamHKShop/Views/Shared/_LayoutThongTin.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>HK Shop</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Thongtin.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

</head>
<body>
    <div class="container">
        <div class="header">
            <div class="headertop">
                <div class="logo">
                    <a href="@Url.Action("Index","HKShop")" style="font-weight: bold; font-size: 18px; text-decoration: none;">
                        <img src="~/images/logo.png" alt="" width="140px" height="100px"/><span>SHOP</span>
                    </a>
                </div>
                <div class="lienhe">
                    <span style="font-size: 16px; line-height: 30px; color: blue; width: 230px; display:block; float:left">Giờ làm việc (8:00 - 22:00) </span>
                    <span style="font-size: 16px; line-height: 30px; color: blue;"><img src="~/images/6.png" />0909 112 113</span>
                </div>
                <div class="thongtin">
                    <a href="@Url.Action("Index","HKShop")"> Trang chủ</a>
                    <a href="@Url.Action("Index","GioiThieu")"> Giới thiệu</a>
                    <a href="@Url.Action("Giohang","Giohang")"> Đơn hàng</a>
                    <a href="@Url.Action("BaoHanh", "HKShop")"> Bảo hành</a>
                    <a href="#"> Tin tức</a>
                    <a href="#"> Khuyến mãi</a>
                    <a href="@Url.Action("Index","Contact")"> Liên hệ</a>
                </div>

                <div class="right">
                    @Html.Action("GioHangPartial", "GioHang")
                    @Html.Partial("LoginPartial")
                </div>
            </div> <!-- Hết header_top-->
        </div>
        <div class="content">              
               @RenderBody()
        </div>
        <div class="footer">
            <div class="left">
                <a href="#" id="btn_logo" style="margin-left: 15px; margin-top: 15px;"><img src="/images/logo.png" width="150px" height="75px" sizes="50" /></a> <br />
                <span><img src="/images/5.png" /> Địa chỉ: 111 - Quận 9 - TPHCM</span> <br />
                <span><img src="/images/6.png" /> Diện thoại: 0909 112 113 - 0909 009 009</span> <br />
                <span><img src="/images/11.png" /> Mail: hkshop123@gmail.com</span>
            </div>
            <div class="center">
                <p style="margin-top:24px; margin-bottom: 10px; font-weight:bold;padding-left: 25px;">THÔNG TIN VÀ HƯỚNG DẪN</p> <br />
                <a id="noidung" href="@Url.Action("Index","GioiThieu")"><span>></span> Giới thiệu</a> <br />
                <a id="noidung" href="#"><span>></span> Hướng dẫn mua hàng</a> <br />
                <a id="noidung" href="#"><span>></span> Các hình thức thanh toán</a> <br />
                <a id="noidung" href="#"><span>></span> Điều khoản sử dụng</a> <br />
                <a id="noidung" href="@Url.Action("BaoHanh", "HKShop")"><span>></span> Bảo hành, đổi trả hàng</a> <br />
                <a id="noidung" href="#"><span>></span> Chính sách bảo mật</a> <br />
            </div>
            <div class="right">
                <p style="margin-top:24px; margin-bottom: 10px; font-weight:bold;padding-left: 25px;">KẾT NỐI VỚI CHÚNG TÔI</p> <br />
                <a href="#" id="icon"><img src="/images/12.png" /></a>
                <a href="#" id="icon"><img src="/images/13.png" /></a>
                <a href="#" id="icon"><img src="/images/14.png" /></a>
                <a href="#" id="icon"><img src="/images/15.png" /></a>
                <a href="#" id="icon"><img src="/images/16.png" /></a>
                <br />
                <p style="margin-top:24px; margin-bottom:-5px; font-weight:bold;padding-left: 25px;">THANH TOÁN ONLINE</p>
                <a id="icon2"><img src="/images/17.png" /></a>
                <a id="icon2"><img src="/images/18.png" /></a>
                <a id="icon2"><img src="/images/19.png" /></a>
                <a id="icon2"><img src="/images/20.png" /></a>

            </div>
        </div> <!-- Hết footer -->

    </div> <!-- Hết container -->
</body>
</html>

WebVanPhongPhamHKShop/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>HK Shop</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="/Content/Style.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="headertop">
                <div class="logo">
                    <a href="@Url.Action("Index","HKShop")" style="font-weight: bold; font-size: 18px; text-decoration: none;"><img src="~/images/logo.png" alt="" width="140px" height="100px"><span>SHOP</span></a>
                </div>
                <div class="lienhe">
                    <span style="font-size: 16px; line-height: 30px; color: blue; width: 230px; display:block; float:left">Giờ làm việc (8:00 - 22:00) </span>
                    <span style="font-size: 16px; line-height: 30px; color: blue;"><img src="~/images/6.png" />0909 112 113</span>
                </div>
                <div class="thongtin">
                    <a href="@Url.Action("Index","HKShop")"> Trang chủ</a>
                    <a href="@Url.Action("Index","GioiThieu")"> Giới thiệu</a>
                    <a href="@Url.Action("Giohang","Giohang")"> Đơn hàng</a>
                    <a href="@Url.Action("BaoHanh", "HKShop")"> Bảo hành</a>
                    <a href="#"> Tin tức</a>
                    <a href="#"> Khuyến mãi</a>
                    <a href="@Url.Action("Index","Contact")"> Liên hệ</a>
                </div>
                
                <div class="right">
                    @Html.Action("GioHangPartial", "GioHang")
                    @Html.Partial("LoginPartial")
                </div>
            </div> <!-- Hết header_top-->
        </div>
        <div class="content">
            <div class="left">
                <div class="danhmuc" style="width: 265px">
                    <h3><img src="/images/7.png" /> DANH MỤC</h3>
                    @Html.Action("DanhMuc", "HKShop")
                </div>
            </div>
            <div class="right">
                <div class="slider">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!-- Nút bấm tròn đặt ở đây -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                            <li data-target="#myCarousel" data-slide-to="3"></li>
                        </ol>
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="~/images/a1.jpg" width="800px" >
                                <!-- thêm caption cho ảnh ở đây -->
                            </div>
                            <div class="item">
                                <img src="~/images/a2.jpg" width="800px" >
                                <!-- thêm caption cho ảnh ở đây -->
                            </div>
                            <div class="item">
                                <img src="~/images/a4.jpg" width="800px" >
                                <!-- thêm caption cho ảnh ở đây -->
                            </div>
                            <div class="item">
                                <img src="~/images/bb.jpg" width="800px" >
                                <!-- thêm caption cho ảnh ở đây -->
                            </div>
                        </div>
                        <!-- Nút next và prev đặt ở đây -->

                    </div>
                </div>

                <div class="body">
                    @RenderBody()
                </div>
            </div>
            
        </div>
        

        <div class="footer">
            <div class="left">
                <a href="#" id="btn_logo" style="margin-left: 15px; margin-top: 15px;"><img src="/images/logo.png" width="150px" height="75px" sizes="50" /></a> <br />
                <span><img src="/images/5.png" /> Địa chỉ: 111 - Quận 9 - TPHCM</span> <br />
                <span><img src="/images/6.png" /> Diện thoại: 0909 112 113 - 0909 009 009</span> <br />
                <span><img src="/images/11.png" /> Mail: hkshop123@gmail.com</span>
            </div>
            <div class="center">
                <p style="margin-top:24px; margin-bottom: 10px; font-weight:bold;padding-left: 25px;">THÔNG TIN VÀ HƯỚNG DẪN</p> <br />
                <a id="noidung" href="@Url.Action("Index","GioiThieu")"><span>></span> Giới thiệu</a> <br />
                <a id="noidung" href="#"><span>></span> Hướng dẫn mua hàng</a> <br />
                <a id="noidung" href="#"><span>></span> Các hình thức thanh toán</a> <br />
                <a id="noidung" href="#"><span>></span> Điều khoản sử dụng</a> <br />
                <a id="noidung" href="@Url.Action("BaoHanh", "HKShop")"><span>></span> Bảo hành, đổi trả hàng</a> <br />
                <a id="noidung" href="#"><span>></span> Chính sách bảo mật</a> <br />
            </div>
            <div class="right">
                <p style="margin-top:24px; margin-bottom: 10px; font-weight:bold;padding-left: 25px;">KẾT NỐI VỚI CHÚNG TÔI</p> <br />
                <a href="#" id="icon"><img src="/images/12.png" /></a>
                <a href="#" id="icon"><img src="/images/13.png" /></a>
                <a href="#" id="icon"><img src="/images/14.png" /></a>
                <a href="#" id="icon"><img src="/images/15.png" /></a>
                <a href="#" id="icon"><img src="/images/16.png" /></a>
                <br />
                <p style="margin-top:24px; margin-bottom:-5px; font-weight:bold;padding-left: 25px;">THANH TOÁN ONLINE</p>
                <a id="icon2"><img src="/images/17.png" /></a>
                <a id="icon2"><img src="/images/18.png" /></a>
                <a id="icon2"><img src="/images/19.png" /></a>
                <a id="icon2"><img src="/images/20.png" /></a>

            </div>
        </div> <!-- Hết footer -->

    </div> <!-- Hết container -->
</body>
</html>