WebVanPhongPhamHKShop/Controllers/HKShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebVanPhongPhamHKShop.Models;
using PagedList;
using PagedList.Mvc;

namespace WebVanPhongPhamHKShop.Controllers
{
    public class HKShopController : Controller
    {
        dbQLVanPhongPhamDataContext data = new dbQLVanPhongPhamDataContext();//Tao database de goi table

        private List<MatHang> LayMatHangMoi(int count)
        {
            return data.MatHangs.OrderByDescending(a => a.NgaySX).Take(count).ToList();//lay cac mat hang moi, so luong la count
            
        }

        public ActionResult Index(int ? page)
        {
            int pageSize = 6;//Tao bien quy dinh so san pham tren 1 trang
            int pageNum = (page ?? 1);//tao bien so trang
            var MHMoi = LayMatHangMoi(10);//Lay 10 mat hang moi
            return View(MHMoi.ToPagedList(pageNum,pageSize));//tao view hien thi 5 mat hang moi
        }

        public ActionResult DanhMuc()
        {
            var danhMuc = from dm in data.DanhMucs select dm;
            return PartialView(danhMuc);//PartialView hien thi danh muc tai menu, can them code vao _LayoutUser o cho menu de hien thi dung
        }

        public ActionResult SPTheoDanhMuc(int id)
        {
            var mH = from s in data.MatHangs where s.MaDM == id select s;//Hien thi san pham theo danh muc
            return View(mH);
        }

        public ActionResult Detail(int id)
        {
            var mH = from s in data.MatHangs where s.MaMH == id select s;//Hien thi thong tin chi tiet san pham
            return View(mH.Single());
        }

        public ActionResult BaoHanh()
        {
            return View();
        }
    }
}

WebVanPhongPhamHKShop/Views/HKShop/BaoHanh.cshtml
@{
    ViewBag.Title = "BaoHanh";
    Layout = "~/Views/Shared/_LayoutThongTin.cshtml";
}

<h2>Bảo hành</h2>
<div class="columns col1-layout">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="page messages"> <div data-placeholder="messages"></div> <div data-bind="scope: 'messages'"><!-- ko if: cookieMessages && cookieMessages.length > 0 --><!-- /ko --><!-- ko if: messages().messages && messages().messages.length > 0 --><!-- /ko --></div></div><div class="column main">
                    <input name="form_key" type="hidden" value="padcXUnF4Riyg1rl"> <div id="authenticationPopup" data-bind="scope:'authenticationPopup'" style="display: none;">
                        <!-- ko template: getTemplate() -->
                        <!-- /ko -->
                    </div>    <div class="chinh-sach-bao-hanh">
                        <h1><img title="Chính sách bảo hành chu đáo" src="https://vmaxcdn.beehexa.com/pub/media/wysiwyg/CMS/BannerTop.jpg" alt="Chính sách bảo hành chu đáo" width="870" height="191"></h1>
                        <p><span>Với mục tiêu mang đến cho khách hàng sự hài lòng, an tâm khi mua hàng, sử dụng dịch vụ tại VMAX, chúng tôi có những chính sách chăm sóc khách hàng chu đáo và tận tâm. Nếu gặp bất kỳ trục trặc kỹ thuật gì, khách hàng có thể liên hệ VMAX để được hướng dẫn bảo hành và tư vấn&nbsp;<strong>miễn phí</strong>.&nbsp;</span></p>             
                        <ul>
                            <li><span>Phiếu bảo hành&nbsp;được đóng gói bên trong hộp sản phẩm</span></li>
                            <li><span>Mục&nbsp;"Thông tin sản phẩm"&nbsp;tại trang sản phẩm<br><br></span></li>
                        </ul><h3><span>I. &nbsp;&nbsp;ĐIỀU KIỆN BẢO HÀNH</span></h3>
                        <p><span><br></span></p>
                        <h3><strong>1. Sản phẩm được bảo hành miễn phí nếu đảm bảo tất cả các điều kiện sau</strong></h3>
                        <ul>
                            <li>Sản phẩm thuộc danh mục được bảo hành từ Nhà sản xuất hoặc Nhà phân phối.</li>
                            <li>Sản phẩm bị lỗi kỹ thuật do Nhà sản xuất.</li>
                            <li>Còn thời hạn bảo hành được tính kể từ khi giao hàng (thời gian bảo hành sẽ được thể hiện cụ thể theo từng sản phẩm)</li>
                            <li>Phiếu bảo hành còn nguyên vẹn, không chắp vá, không bị gạch xóa hay sửa chữa, bôi bẩn.</li>
                            <li>Phiếu bảo hành đầy đủ thông tin: mã sản phẩm, số seri, ngày sản xuất, tên khách hàng sử dụng, địa chỉ, ngày mua (đối với các sản phẩm không áp dụng Bảo hành điện tử).</li>
                            <li>Tem bảo hành và tem niêm phong (nếu có) của Nhà sản xuất hay nhà phân phối trên sản phẩm còn nguyên vẹn.</li>
                        </ul><div>&nbsp;</div>
                        <h3><strong>2. Sản phẩm không được bảo hành hoặc sẽ phát sinh phí bảo hành nếu rơi vào một trong các trường hợp sau</strong></h3>
                        <ul>
                            <li>Sản phẩm không thuộc danh mục được bảo hành từ Nhà sản xuất hoặc nhà phân phối.</li>
                            <li>Sản phẩm không thỏa mãn một trong những điều kiện bảo hành ở mục điều kiện bảo hành (Sản phẩm đã hết thời gian bảo hành; Phiếu, tem bảo hành: Không có hoặc bị rách nát, sửa đổi; Số mã vạch, serial trên sản phẩm không xác định được; Sản phẩm lỗi không được bảo quản trong bao đen)</li>
                            <li>Số series, model sản phẩm không khớp với Phiếu bảo hành.</li>
                            <li>Khách hàng tự ý can thiệp sửa chữa, tháo dỡ sản phẩm hoặc sửa chữa tại những trung tâm bảo hành không được sự ủy nhiệm của Nhà sản xuất hoặc của VMAX.</li>
                            <li>Sản phẩm bị cháy nổ, hỏng hóc do tác động cơ học, biến dạng, trầy xước, ẩm ướt, hoen rỉ, chảy nước, động vật xâm nhập vào, thiên tai, sử dụng không đúng quy định.</li>
                        </ul><div>&nbsp;</div>
                        <h3><strong>&nbsp;3.&nbsp;Chi tiết bảo hành cho từng nhóm</strong></h3>
                        <p><strong><br></strong></p>
                        <p><span><img title="Điều kiện bảo hành" src="https://vmaxcdn.beehexa.com/pub/media/wysiwyg/CMS/Banner2_1.jpg" alt="Điều kiện bảo hành" width="870" height="186"><br></span></p>
                        
                        <h3><span>II. HƯỚNG DẪN BẢO HÀNH</span></h3>
                        <p><span><br></span></p>
                        <h3><strong>1. Hướng dẫn cách thức bảo hành</strong></h3>
                        <p><span>Quý khách có thể liên hệ trực tiếp với Trung tâm Bảo hành của Nhà cung cấp/Nhà Phân phối sản phẩm theo thông tin trong phiếu bảo hành.</span></p>
                        
                        <p><span><br></span></p>
                        <h3><span>&nbsp;<strong>2</strong>.&nbsp;</span><strong>Thời gian thực hiện bảo hành</strong></h3>
                        <p><span>Trong mọi trường hợp, thời gian thực hiện bảo hành sản phẩm phụ thuộc vào chính sách và/hoặc mức độ sẵn có của thiết bị/sản phẩm thay thế của Trung Tâm Bảo Hành và sẽ được thông báo cụ thể cho Quý khách vào thời điểm nhận sản phẩm để bảo hành.</span></p>
                        <p><span>Trong mọi trường hợp, công ty không chịu trách nhiệm về bất kỳ thiệt hại, mất mát nào xảy ra nếu Quý khách không thực hiện theo hướng dẫn tại Chính sách bảo hành này.</span></p>
                        <p><span>&nbsp;</span></p>
                        <h2><strong>BẢO TRÌ</strong><strong>, SỬA CHỮA</strong></h2>
                        <p><span>Chúng tôi còn bảo trì định kỳ và sửa chữa&nbsp;<strong>miễn phí</strong>&nbsp;cho <a class="crosslink" href="https://www.vmax.vn/may-in-van-phong-1773.html" target="_blank" alt="Máy in" title="Máy in">máy in</a>, <a class="crosslink" href="https://www.vmax.vn/may-van-phong/may-photocopy-1810.html" target="_blank" alt="Máy photocopy" title="Máy photocopy">máy photocopy</a> của Quý khách&nbsp;<strong>3 tháng 1 lần</strong>, để đảm bảo cho <a class="crosslink" href="https://www.vmax.vn/may-in-van-phong-1773.html" target="_blank" alt="Máy in" title="Máy in">máy in</a> của Quý khách luôn sẵn sàng thực hiện lệnh in, cho ra bản in chất lượng hoàn hảo. Thêm vào đó, VMAX hỗ trợ sửa chữa tất cả các máy thiết bị văn phòng miễn phí nếu không thay thế vật tư.</span></p>
                        <p><span>Các chính sách bảo hành, bảo trì đều áp dụng cho hàng hoá khi mua hàng online giống như khách hàng mua trực tiếp.</span></p>
                       
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebVanPhongPhamHKShop/Views/HKShop/DanhMuc.cshtml
@model IEnumerable<WebVanPhongPhamHKShop.Models.DanhMuc>
@foreach (var item in Model)
{
    <a href="@Url.Action("SPTheoDanhMuc","HKSHop",new { id=item.MaDM})">@item.TenDM</a>
}

WebVanPhongPhamHKShop/Views/HKShop/Detail.cshtml
<style>
    #DatMua a{
        clear: both;
        background-color:red;
        color:white;
        width:120px;
        height:35px;
        display:block;
        float:right;
        text-align:center;
        padding-top:10px;
        text-decoration:none;
        font-weight:bold;
    }
    #DatMua a:hover{
        background-color:gray;
        color:red;
    }
</style>

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3>Thông tin chi tiết sản phẩm</h3>
<div>
    <div style="width:40%; float:left; border-left:dotted 1px; border-color:azure">
        <img src="~/images/@Model.AnhBia" width="100%" />
    </div>
    <div style="width:60%; float:left; padding:10px">
        <h4 style="font-weight:bold; color:red">@Model.TenMH</h4>
        <p style="text-align:justify"><span style="font-weight:bold">Mô tả: </span>@Model.MoTa</p>
        <p style="font-weight:bold">Giá bán: <span style="color:red; font-size:16pt">@Model.GiaBan VNĐ</span></p>
    </div>
    <div>
        <div id="DatMua">
            <a href="@Url.Action("ThemGioHang", "GioHang",new { @iMaMH= @Model.MaMH, @strURL=Request.Url.ToString() })" class="list-group-item">
            ĐẶT MUA
            </a>
        </div>
    </div>
</div>

WebVanPhongPhamHKShop/Views/HKShop/Index.cshtml
@using WebVanPhongPhamHKShop.Models
@using PagedList.Mvc
@model PagedList.PagedList<MatHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Sản phẩm mới</h2>
@foreach (var MatHang in Model)
{
    @*chay vong foreach hie thi cac mat hang*@
    <div  class="col-sm-4 col-lg-5 col-md-4">
        <div class="thumbnail" style="width:200px; height:250px" >
            <a href="@Url.Action("Detail","HKShop",new { id = MatHang.MaMH })">
                <img src="~/images/@MatHang.AnhBia" alt="@MatHang.TenMH" style="width:70%"/>
                <div>
                    <br />
                    <h4 style="text-align: center;">
                        @MatHang.TenMH
                    </h4>
                    <p></p>
                </div>
            </a>
        </div>
    </div>
}
@* Tao lien ket trang *@
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model,page=>Url.Action("Index",new { page=page}))
</div>
<style>
    .MenuTrang li{
        display:inline;
    }
</style>

WebVanPhongPhamHKShop/Views/HKShop/SPTheoDanhMuc.cshtml
@model IEnumerable<WebVanPhongPhamHKShop.Models.MatHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@foreach (var MatHang in Model)
{
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail" style="width:200px; height:200px">
            <a href="@Url.Action("Detail","HKShop",new { id = MatHang.MaMH })">
                <img src="~/images/@MatHang.AnhBia" alt="@MatHang.TenMH" style="width:58%" />
                <div>
                    <br />
                    <h4 style="text-align:center">
                        @MatHang.TenMH
                    </h4>
                    <p></p>
                </div>
            </a>
        </div>
    </div>
}